export const UPDATE_CATEGORY_PRODUCTS = 'UPDATE_CATEGORY_PRODUCTS';
export const UPDATE_PRICE_FILTER = 'UPDATE_PRICE_FILTER';
export const UPDATE_COLOR_FILTER = 'UPDATE_COLOR_FILTER';
export const UPDATE_SIZE_FILTER = 'UPDATE_SIZE_FILTER';
export const UPDATE_FILTERED_PRODUCTS = 'UPDATE_FILTERED_PRODUCTS';
