# Generated by Django 4.2.7 on 2024-01-25 12:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(error_messages={'unique': 'Email already registered'}, max_length=254, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z0-9_\\.-]+\\@[a-zA-Z]+[a-zA-Z0-9]+\\.[a-z]+(\\.[a-z]+)?', 'Enter a valid email')], verbose_name='email address')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator("[a-zA-Z\\s\\-\\']+", 'Enter a valid name')])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator("[a-zA-Z\\s\\-\\']+", 'Enter a valid name')])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.TextField(max_length=250)),
                ('zipCode', models.CharField(max_length=10)),
                ('address_type', models.PositiveIntegerField(choices=[(1, 'Billing address'), (2, 'Shipping address')])),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
