# Generated by Django 4.2.7 on 2024-01-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='productVariantId',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
