# Generated by Django 4.2.7 on 2024-01-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productsizecollection_size'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='productColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcolor'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='productSize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productsize'),
        ),
    ]
