# Generated by Django 4.2.7 on 2024-01-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.CreateModel(
            name='ProductSizeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.productsize')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.ManyToManyField(related_name='product_variant_sizes', through='product.ProductSizeCollection', to='product.productsize'),
        ),
    ]
