# Generated by Django 4.2.7 on 2024-01-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_productimages_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagesitem',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.productimage'),
        ),
    ]
