# Generated by Django 4.2.7 on 2024-01-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productsize_quantity_alter_productvariant_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productsizecollection',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
