# Generated by Django 4.2.7 on 2024-01-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productsize_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='size',
            new_name='sizes',
        ),
    ]
