# Generated by Django 4.2.7 on 2024-01-12 15:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimagesitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagecolor',
            name='hexValue',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=25, samples=None),
        ),
    ]
