# Generated by Django 4.2.7 on 2024-01-12 17:33

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimagecolor_hexvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='productimage',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productimagecolor'),
        ),
        migrations.AlterField(
            model_name='productimagecolor',
            name='hexValue',
            field=colorfield.fields.ColorField(default='#000', editable=False, image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='productimagesitem',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productimagesitem',
            name='size',
            field=models.ManyToManyField(to='product.productsize'),
        ),
    ]
