# Generated by Django 4.2.7 on 2024-01-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_size_productvariant_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizecollection',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsize'),
        ),
    ]
