# Generated by Django 4.2.7 on 2024-01-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productsize_productimage_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimagesitem',
            name='size',
        ),
        migrations.AddField(
            model_name='productimage',
            name='size',
            field=models.ManyToManyField(to='product.productsize'),
        ),
    ]
